### get all
GET http://localhost:3000/api/flights

### get one
GET http://localhost:3000/api/flights/1

### create
POST http://localhost:3000/api/flights 
Content-Type: application/json

{
    "fechahora_salida":  "2026-02-08 10:00", 
    "fechahora_llegada": "2026-02-08 18:00", 
    "duracion": 6, 
    "aerolinea": "American Airlines",
    "cantidad_asientos": 200
}

### modificar recurso completo e idempotente
PUT http://localhost:3000/api/flights/b6a77cb4-qfae-qef2-ae83-ffb11f09e9b4  
Content-Type: application/json

{
    "fechahora_salida":  "4 de junio 2026 12:00", 
    "fechahora_llegada": "4 de junio 2026 20:00", 
    "duracion": 8, 
    "aerolinea": "flybondi",
    "cantidad_asientos": 130
}

### modificar recurso parcial
PATCH http://localhost:3000/api/flights/b6a77cb4-qfae-qef2-ae83-ffb11f09e9b4  
Content-Type: application/json

{
    "duracion":  "5", 
    "cantidad_asientos": "80"
}

###borrar recurso
DELETE http://localhost:3000/api/flights/b6a77cb4-qfae-qef2-ae83-ffb11f09e9b4